name: Generar APK

on:
  workflow_dispatch:
  push:
    branches:
      - principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v6

      - name: Preparar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Preparar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.7'

      - name: Descomprimir proyecto
        run: |
          unzip -o cuentas-claras-final-v2.zip
          ls -la
          ls -la cuentas-claras-final

      - name: Construir APK
        working-directory: cuentas-claras-final
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: cuentas-claras-apk
          path: cuentas-claras-final/app/build/outputs/apk/debug/app-debug.apk
